//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encargos
    {
        public float Enc13 { get; set; }
        public float AvisoPrevio { get; set; }
        public float Ferias { get; set; }
        public float FGTS { get; set; }
        public float INSS { get; set; }
        public int EmpresaCod { get; set; }
        public float INCRA { get; set; }
        public float SalEducacao { get; set; }
        public float Sebrae { get; set; }
        public float Senai { get; set; }
        public float SESI { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
