//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Afastamento = new HashSet<Afastamento>();
            this.CalculoEventoBase = new HashSet<CalculoEventoBase>();
            this.SolicitacaoAlteracaoCargo = new HashSet<SolicitacaoAlteracaoCargo>();
            this.SolicitacaoAlteracaoSalario = new HashSet<SolicitacaoAlteracaoSalario>();
            this.SolicitacaoDesligamento = new HashSet<SolicitacaoDesligamento>();
            this.ValoresAbertosBase = new HashSet<ValoresAbertosBase>();
            this.AdNoturnoBase = new HashSet<AdNoturnoBase>();
            this.HEBase = new HashSet<HEBase>();
            this.SimulacaoDemissao = new HashSet<SimulacaoDemissao>();
            this.FuncionarioFerias = new HashSet<FuncionarioFerias>();
            this.Transferencia = new HashSet<Transferencia>();
        }
    
        public string Matricula { get; set; }
        public float AuxCreche { get; set; }
        public float AuxEducacao { get; set; }
        public float AuxFilhoExc { get; set; }
        public float PrevidenciaPrivada { get; set; }
        public float AuxSeguro { get; set; }
        public System.DateTime DataAdmissao { get; set; }
        public Nullable<System.DateTime> MesDesligamento { get; set; }
        public string Nome { get; set; }
        public bool Periculosidade { get; set; }
        public int QtdaDependentes { get; set; }
        public float Salario { get; set; }
        public string TipoAviso { get; set; }
        public string CentroCustoCod { get; set; }
        public string CidadeNome { get; set; }
        public int EmpresaCod { get; set; }
        public int CargaHoraria { get; set; }
        public string Situacao { get; set; }
        public int CargoCod { get; set; }
        public int SindicatoCod { get; set; }
        public Nullable<int> ConvenioMedCod { get; set; }
        public float ValorConvMedico { get; set; }
        public float ValorConvOdontologico { get; set; }
        public bool AdCondutor { get; set; }
        public bool VTFretadoFlag { get; set; }
        public int CodEscalaTrabalho { get; set; }
        public Nullable<int> CodConvenioOdo { get; set; }
        public bool RecebeVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Afastamento> Afastamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalculoEventoBase> CalculoEventoBase { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual ConvenioMed ConvenioMed { get; set; }
        public virtual Sindicato Sindicato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitacaoAlteracaoCargo> SolicitacaoAlteracaoCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitacaoAlteracaoSalario> SolicitacaoAlteracaoSalario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitacaoDesligamento> SolicitacaoDesligamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoresAbertosBase> ValoresAbertosBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdNoturnoBase> AdNoturnoBase { get; set; }
        public virtual ConvenioOdo ConvenioOdo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEBase> HEBase { get; set; }
        public virtual Variaveis Variaveis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulacaoDemissao> SimulacaoDemissao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionarioFerias> FuncionarioFerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        public virtual EscalaTrabalho EscalaTrabalho { get; set; }
        public virtual Filial Filial { get; set; }
    }
}
