//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReajConvenioOdo
    {
        public int Ano { get; set; }
        public int CodConvenioOdo { get; set; }
        public int MesReajuste { get; set; }
        public float PercentualReajuste { get; set; }
    
        public virtual ConvenioOdo ConvenioOdo { get; set; }
    }
}
