//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simulacao()
        {
            this.SimulacaoContratacao = new HashSet<SimulacaoContratacao>();
            this.SimulacaoDemissao = new HashSet<SimulacaoDemissao>();
        }
    
        public int Codigo { get; set; }
        public int TipoSimulacaoCod { get; set; }
        public string Descricao { get; set; }
        public string CodigoCR { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int MesOrcamentoCod { get; set; }
    
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual TipoSimulacao TipoSimulacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulacaoContratacao> SimulacaoContratacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulacaoDemissao> SimulacaoDemissao { get; set; }
        public virtual MesOrcamento MesOrcamento { get; set; }
    }
}
