//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulacaoContratacao
    {
        public int Codigo { get; set; }
        public int SimulacaoCod { get; set; }
        public string CidadeNome { get; set; }
        public int CargoCod { get; set; }
        public int EmpresaCod { get; set; }
        public int CargaHoraria { get; set; }
        public float Salario { get; set; }
        public Nullable<int> ConvenioMedCod { get; set; }
        public Nullable<int> ConvenioOdoCod { get; set; }
        public bool VTFretadoFlag { get; set; }
        public bool Periculosidade { get; set; }
    
        public virtual ConvenioMed ConvenioMed { get; set; }
        public virtual ConvenioOdo ConvenioOdo { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Simulacao Simulacao { get; set; }
        public virtual Variaveis Variaveis { get; set; }
    }
}
