//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afastamento
    {
        public System.DateTime DataInicio { get; set; }
        public string MatriculaFuncionario { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string Motivo { get; set; }
        public int Codigo { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
