//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReajVTPasse
    {
        public int Ano { get; set; }
        public double PercentualReajuste { get; set; }
        public Nullable<int> MesReajuste { get; set; }
        public string CidadeNome { get; set; }
    
        public virtual Cidade Cidade { get; set; }
    }
}
