//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita
    {
        public string Atividade { get; set; }
        public string CentroCustoCod { get; set; }
        public System.DateTime Mes { get; set; }
        public double Valor { get; set; }
    
        public virtual CentroCusto CentroCusto { get; set; }
    }
}
