//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario
    {
        public int CargoCod { get; set; }
        public int CargaHoraria { get; set; }
        public int EmpresaCod { get; set; }
        public string CidadeNome { get; set; }
        public Nullable<float> Faixa1 { get; set; }
        public Nullable<float> Faixa2 { get; set; }
        public Nullable<float> Faixa3 { get; set; }
        public Nullable<float> Faixa4 { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Variaveis Variaveis { get; set; }
    }
}
