//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitacaoContratacao
    {
        public int SolicitacaoCod { get; set; }
        public string CidadeNome { get; set; }
        public int CargoCod { get; set; }
        public int CargaHoraria { get; set; }
        public int EmpresaCod { get; set; }
        public string CRDestino { get; set; }
        public float Salario { get; set; }
        public int Qtda { get; set; }
        public System.DateTime DataPrevista { get; set; }
    
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual SolicitacaoTH SolicitacaoTH { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Variaveis Variaveis { get; set; }
    }
}
