//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitacaoTH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitacaoTH()
        {
            this.ACTs = new HashSet<ACT>();
            this.STHs = new HashSet<STH>();
        }
    
        public int Codigo { get; set; }
        public string TipoSolicitacao { get; set; }
        public string LoginSolicitante { get; set; }
        public System.DateTime DataSolicitacao { get; set; }
        public string Parecer { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
        public string DescricaoResposta { get; set; }
        public string DescricaoSolicitacao { get; set; }
        public string StatusSolicitacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT> ACTs { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STH> STHs { get; set; }
        public virtual SolicitacaoAlteracaoSalario AlteracaoSalario { get; set; }
        public virtual SolicitacaoContratacao Contratacao { get; set; }
        public virtual SolicitacaoDesligamento Desligamento { get; set; }
        public virtual SolicitacaoAlteracaoCargo SolicitacaoAlteracaoCargo { get; set; }
    }
}
