//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitacaoAlteracaoSalario
    {
        public int SolicitacaoCod { get; set; }
        public string FuncionarioMatricula { get; set; }
        public float SalarioAnterior { get; set; }
        public float SalarioNovo { get; set; }
    
        public virtual SolicitacaoTH SolicitacaoTH { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
