//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public string CRDestino { get; set; }
        public string FuncionarioMatricula { get; set; }
        public string Status { get; set; }
        public System.DateTime DataSolicitacao { get; set; }
        public int MesTransferencia { get; set; }
    
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual MesOrcamento MesOrcamento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
